export const SCREENS = {
  navigators: {
    auth: 'Auth Navigator',
    home: 'Home Navigator',
    tabs: 'Tab Navigator',
    onboard: 'Onboarding Navigator',
  },
  onBoard: {
    splash: 'Splash Screen',
    onboarding: 'Onboarding Screen',
  },
  auth: {
    login: 'Login Screen',
    forgotPassword: 'Forgot Password Screen',
    changedPassword: 'Password Change Screen',
    resetPassword: 'Reset Password Screen',
    ageConfirmation: 'Age Confirmation Screen',
    checkInbox: 'Check Inbox Screen',
    congrats: 'Congratulations Screen',
    confirmOTP: 'Confirm OTP Screen',
    resetPasswordOtp: 'Reset Password OTP Screen',
    signUp: 'Sign Up Screen',
  },
  home: {
    dashboard: 'Dashboard Screen',
    explore: 'Explore SCreen',
    feeds: 'Feed Screen',
    saved: 'Saved Screen',
    favoriteCategory: 'Favorite Category Screen',
    drinks: 'Drinks Screen',
    blogs: 'Blogs Screen',
    location: 'Location Screen',
    locationCongrats: 'Add Location Congrats Screen',
    card: 'Card Screen',
    spotOfTheWeek: 'Spot of the week',
    club: 'About Club Screen',
    map: 'Club Map Screen',
    allCards: 'All Cards Screen',
  },
  review: {
    review: 'Club Review Screen',
    addReview: 'Add Review Screen',
  },
  drinks: {
    singleDrink: 'Single Drink Screen',
    map: 'Get Directions to Claim Drink Screen',
    congrats: 'Claimed Drinks Congratulations Screen',
    reserve: 'Reserve Table',
  },
  profile: {
    profile: 'Profile Page',
    settings: 'Settings Page',
    editProfile: 'Edit Profile Page',
    notification: 'Notification Page',
    suggestion: 'Suggestion Page',
    rate: 'Rate Page',
    help: 'Help Page',
    privacyPolicy: 'Privacy Policy Page',
    termsOfUse: 'Terms of Use Page',
  },
};
